/* wireguard.js — VAS Mockup: WireGuard page interactivity */
/* Requires: app.js loaded first */

const MOCK_TEMPLATE = `[Interface]
# VAS WireGuard interface — generated by vas
PrivateKey = <PASTE_PRIVATE_KEY_HERE>
Address = 10.8.0.2/24
DNS = 1.1.1.1

[Peer]
PublicKey = <PASTE_SERVER_PUBLIC_KEY_HERE>
PresharedKey = <PASTE_PRESHARED_KEY_HERE>
Endpoint = vpn.example.com:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25`;

const MOCK_VALID_CONFIG = `[Interface]
PrivateKey = aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ=
Address = 10.8.0.2/24
DNS = 1.1.1.1

[Peer]
PublicKey = bBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaA=
PresharedKey = cCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZaAbB=
Endpoint = vpn.homeoffice-vas.io:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25`;

const MOCK_HISTORY = [
  { id: '20260615-142301', path: '/etc/vas/wireguard/history/20260615-142301.conf', valid: true,  content: MOCK_VALID_CONFIG },
  { id: '20260614-091045', path: '/etc/vas/wireguard/history/20260614-091045.conf', valid: true,  content: MOCK_VALID_CONFIG },
  { id: '20260610-163822', path: '/etc/vas/wireguard/history/20260610-163822.conf', valid: false, content: '[Interface]\nPrivateKey = missing_key\nAddress = 10.8.0.2/24\n# [Peer] section missing' },
];

function validate(content) {
  const errors   = [];
  const warnings = [];
  if (!content.includes('[Interface]'))  errors.push('missing [Interface] section');
  if (!content.includes('[Peer]'))       errors.push('missing [Peer] section');
  if (!content.includes('PrivateKey'))   errors.push('missing PrivateKey in [Interface]');
  if (!content.includes('PublicKey'))    errors.push('missing PublicKey in [Peer]');
  if (content.includes('<PASTE_'))       warnings.push('placeholder values detected — replace before use');
  if (!content.includes('Endpoint'))     warnings.push('no Endpoint specified in [Peer]');
  return { valid: errors.length === 0, errors, warnings };
}

function renderValidation(el, v) {
  if (!el) return;
  el.className = `validation-panel ${v.valid ? 'valid' : 'invalid'}`;
  const items = [...v.errors, ...v.warnings];
  el.innerHTML = `<strong>${v.valid ? 'Valid config' : 'Config needs attention'}</strong>
    <ul>${(items.length ? items : ['No validation issues.']).map((m) => `<li>${m}</li>`).join('')}</ul>`;
}

function setResult(message, status = '') {
  const el = document.getElementById('wireguardResult');
  if (!el) return;
  el.className = `apply-result ${status}`;
  el.textContent = message;
}

// ── Config editor ─────────────────────────────────────────────────
function initConfigEditor() {
  const textarea   = document.getElementById('wireguardConfig');
  const validation = document.getElementById('configValidation');

  document.getElementById('loadTemplate')?.addEventListener('click', () => {
    if (!textarea) return;
    textarea.value = MOCK_TEMPLATE;
    renderValidation(validation, validate(MOCK_TEMPLATE));
    setResult('Template loaded.', 'success');
    showToast('New template loaded.', 'info');
  });

  document.getElementById('validateConfig')?.addEventListener('click', () => {
    if (!textarea) return;
    const v = validate(textarea.value);
    renderValidation(validation, v);
    setResult(v.valid ? 'Config is valid.' : 'Config has validation issues.', v.valid ? 'success' : 'error');
    showToast(v.valid ? 'Config valid.' : 'Validation issues found.', v.valid ? 'success' : 'error');
  });

  document.getElementById('saveConfig')?.addEventListener('click', () => {
    if (!textarea) return;
    const v = validate(textarea.value);
    renderValidation(validation, v);
    setResult('Saved /etc/vas/wireguard/wg0.conf.', 'success');
    showToast('Config saved.', 'success');
    addHistoryEntry();
  });

  document.getElementById('deleteConfig')?.addEventListener('click', async () => {
    const ok = await showConfirmModal({
      title: 'ลบ App Config',
      message: 'ต้องการลบไฟล์ WireGuard config ที่บันทึกไว้ (/etc/vas/wireguard/wg0.conf) หรือไม่? การกระทำนี้ไม่สามารถย้อนกลับได้',
      confirmLabel: 'ลบ',
      cancelLabel: 'ยกเลิก',
      variant: 'danger',
    });
    if (!ok) return;
    if (textarea) textarea.value = '';
    renderValidation(validation, { valid: false, errors: ['missing [Interface] section', 'missing [Peer] section'], warnings: [] });
    setResult('Deleted /etc/vas/wireguard/wg0.conf.', 'success');
    showToast('Config deleted.', 'error');
  });
}

// ── Actions (sync / unsync) ───────────────────────────────────────
function initActions() {
  document.querySelectorAll('[data-wireguard-action]').forEach((btn) => {
    btn.addEventListener('click', async () => {
      const action = btn.dataset.wireguardAction;
      const isSync = action === 'sync';
      const ok = await showConfirmModal({
        title: isSync ? 'Sync Active Config' : 'Unsync Active Config',
        message: isSync
          ? 'จะนำ config ที่บันทึกไว้ไปใช้กับ WireGuard บนระบบ และ restart interface wg0 ต้องการดำเนินการต่อหรือไม่?'
          : 'จะปิดการใช้งาน config บนระบบ และสำรอง config ปัจจุบัน ต้องการดำเนินการต่อหรือไม่?',
        confirmLabel: isSync ? 'Sync' : 'Unsync',
        cancelLabel: 'ยกเลิก',
        variant: isSync ? 'info' : 'caution',
      });
      if (!ok) return;

      setResult(`${isSync ? 'Syncing' : 'Unsyncing'} active config...`);
      setTimeout(() => {
        if (isSync) {
          setResult('Sync completed — wg0 interface restarted.', 'success');
          showToast('WireGuard synced and restarted.', 'success');
          updateStatusBadge('cf-zone-safe', 'Connected');
        } else {
          setResult('Unsync completed — service disabled, config backed up.', 'success');
          showToast('WireGuard unsynced.', 'info');
          updateStatusBadge('cf-zone-mute', 'Disconnected');
        }
        addHistoryEntry();
      }, 1000);
    });
  });
}

function updateStatusBadge(cls, label) {
  const badge = document.getElementById('connectionBadge');
  if (!badge) return;
  badge.className = `cf-zone ${cls}`;
  badge.textContent = label;
}

// ── History ────────────────────────────────────────────────────────
let _historyEntries = [...MOCK_HISTORY];

function addHistoryEntry() {
  const now = new Date();
  const id  = now.toISOString().replace(/[-T:]/g, '').slice(0, 15);
  _historyEntries = [
    { id, path: `/etc/vas/wireguard/history/${id}.conf`, valid: true, content: MOCK_VALID_CONFIG },
    ..._historyEntries,
  ];
  renderHistory();
}

function renderHistory() {
  const list = document.getElementById('historyList');
  if (!list) return;

  list.innerHTML = '';
  if (!_historyEntries.length) {
    list.innerHTML = '<p style="padding:1rem;color:rgb(var(--c-faint));font-size:0.82rem;">No history snapshots found.</p>';
    return;
  }
  _historyEntries.forEach((entry) => {
    const wrapper = document.createElement('div');
    wrapper.className = 'history-entry';
    wrapper.dataset.historyId = entry.id;
    wrapper.innerHTML = `
      <button class="history-item" type="button">
        <div class="history-item-main">
          <span class="history-item-id">${entry.id}</span>
          <span class="history-item-path">${entry.path}</span>
        </div>
        <span class="cf-zone ${entry.valid ? 'cf-zone-safe' : 'cf-zone-caution'}">${entry.valid ? 'Valid' : 'Invalid'}</span>
      </button>
      <div class="history-accordion" hidden>
        <div class="validation-panel ${entry.valid ? 'valid' : 'invalid'}">
          <strong>${entry.valid ? 'Valid config' : 'Config needs attention'}</strong>
          <ul>${entry.valid ? '<li>No validation issues.</li>' : '<li>placeholder values detected</li>'}</ul>
        </div>
        <pre class="config-pre" style="margin-top:0.5rem;">${escHtml(entry.content)}</pre>
        <div style="display:flex;justify-content:flex-end;margin-top:0.5rem;">
          <button class="cf-btn cf-btn-danger delete-history-btn" type="button">Delete snapshot</button>
        </div>
      </div>`;

    wrapper.querySelector('.history-item').addEventListener('click', () => {
      const acc = wrapper.querySelector('.history-accordion');
      const btn = wrapper.querySelector('.history-item');
      const isOpen = !acc.hidden;
      document.querySelectorAll('.history-accordion').forEach((a) => { a.hidden = true; });
      document.querySelectorAll('.history-item').forEach((b) => b.classList.remove('open'));
      if (!isOpen) {
        acc.hidden = false;
        btn.classList.add('open');
      }
    });

    wrapper.querySelector('.delete-history-btn').addEventListener('click', async () => {
      const ok = await showConfirmModal({
        title: 'ลบ Snapshot',
        message: `ต้องการลบ snapshot ${entry.id} หรือไม่? ไฟล์จะถูกลบออกจากประวัติอย่างถาวร`,
        confirmLabel: 'ลบ',
        cancelLabel: 'ยกเลิก',
        variant: 'danger',
      });
      if (!ok) return;
      _historyEntries = _historyEntries.filter((e) => e.id !== entry.id);
      setResult(`Deleted history ${entry.id}.`, 'success');
      showToast(`Snapshot ${entry.id} deleted.`, 'info');
      renderHistory();
    });

    list.appendChild(wrapper);
  });
}

function escHtml(str) {
  return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// ── Refresh history button ────────────────────────────────────────
function initRefreshHistory() {
  document.getElementById('refreshHistory')?.addEventListener('click', () => {
    showToast('History refreshed (mock).', 'info');
    renderHistory();
  });
}

// ── Boot ─────────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', () => {
  initConfigEditor();
  initActions();
  initRefreshHistory();
  renderHistory();
});
